Update unit-test.yml

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -49,3 +49,8 @@ jobs:
         run: |
           cd projects/scllib 
           npm run test
+      - name: Cleanup & Upload Coverage
+        shell: bash
+        run: |
+          rm -rf .tmp
+          bash <(curl -s https://codecov.io/bash) -c -K || echo "Codecov upload failed"
